# This is a basic workflow to help you get started with Actions

name: OpenAPI Doc Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  openApiDocBuilder:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - run: mkdir --parents output
      # Runs a single command using the runners shell
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with: 
          output: output
          spec-file: insomnia.json
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: output
